# Generated by Django 5.0.2 on 2024-08-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("sir_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("county", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("case_number", models.TextField(max_length=100)),
                ("matter_number", models.CharField(max_length=100)),
                ("matter_name", models.CharField(max_length=100)),
                ("document_upload", models.FileField(upload_to="documents/")),
                ("description", models.TextField()),
                (
                    "pleading_status",
                    models.CharField(
                        choices=[
                            ("plaintiff", "Plaintiff"),
                            ("defendant", "Defendant"),
                        ],
                        max_length=50,
                    ),
                ),
                ("statement", models.TextField()),
                (
                    "dispute",
                    models.CharField(
                        choices=[
                            ("criminal", "Criminal"),
                            ("civil", "Civil"),
                            ("other", "Other Services"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "criminal_sub_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("option1", "Option 1"),
                            ("option2", "Option 2"),
                            ("option3", "Option 3"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "civil_sub_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("option1", "Option 1"),
                            ("option2", "Option 2"),
                            ("option3", "Option 3"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "other_services_sub_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("option1", "Option 1"),
                            ("option2", "Option 2"),
                            ("option3", "Option 3"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
