# Generated by Django 5.0.2 on 2024-08-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_clients_case_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="clients",
            name="status",
            field=models.CharField(
                choices=[("ongoing", "ongoing"), ("case closed", "case closed")],
                default="ongoing",
                max_length=100,
            ),
        ),
    ]
