# Generated by Django 5.0.2 on 2024-08-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_clients_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("ongoing", "ongoing"), ("case closed", "case closed")],
                default="ongoing",
                max_length=100,
                null=True,
            ),
        ),
    ]
