# Generated by Django 5.0.2 on 2024-08-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_clients_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="courtAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=100)),
                ("matterNumber", models.CharField(max_length=100)),
                ("matterName", models.CharField(max_length=100)),
                ("parties", models.CharField(max_length=100)),
                ("purpose", models.CharField(max_length=100)),
                ("court_presiding", models.CharField(max_length=100)),
                ("advocates", models.CharField(max_length=100)),
                ("timeTaken", models.CharField(max_length=100)),
                ("furtherAction", models.CharField(max_length=100)),
                ("signedBy", models.CharField(max_length=100)),
            ],
        ),
    ]
