# Generated by Django 5.0.2 on 2024-08-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_courtattendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="clients",
            name="billing",
            field=models.CharField(blank=True, default=0.0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="clients",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paid", "Paid"),
                    ("unpaid", "Unpaid"),
                    ("pro Bono", "pro_Bono"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
